apiVersion: v1
kind: Service
metadata:
  name: coredns-blocky
  namespace: homelab-dns
spec:
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
      targetPort: 53
    - port: 53
      name: dns-tcp
      protocol: TCP
      targetPort: 53
  selector:
    app: coredns-blocky
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-blocky
  namespace: homelab-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coredns-blocky
  template:
    metadata:
      labels:
        app: coredns-blocky
    spec:
      containers:
        - name: blocky
          image: spx01/blocky:v0.26.2
          ports:
            - containerPort: 4000
              name: http # prometheus metrics
            - containerPort: 1053
              name: dns-udp
              protocol: UDP
            - containerPort: 1053
              name: dns-tcp
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: BLOCKY_CONFIG_FILE
              value: /etc/blocky/config.yaml
          volumeMounts:
            - name: blocky-config
              mountPath: /etc/blocky
        - name: coredns
          image: coredns/coredns:latest
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
      volumes:
        - name: config-volume
          configMap:
            name: coredns
        - name: blocky-config
          configMap:
            name: blocky-config
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: homelab-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        etcd homelab.local {
          endpoint http://dns-etcd:2379
          path /skydns
          fallthrough
        }
        forward . 127.0.0.1:1053
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: homelab-dns
data:
  config.yaml: |
    upstreams:
      groups:
        default:
          - 192.168.1.254
          - 1.1.1.1
    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      clientGroupsBlock:
        default:
          - ads
    ports:
      dns: 1053
      http: 4000
---
