apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: homelab-dns
spec:
  ports:
    - port: 53
      name: dns-udp
      protocol: UDP
      targetPort: 53
    - port: 53
      name: dns-tcp
      protocol: TCP
      targetPort: 53
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: homelab-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
        - name: coredns
          image: coredns/coredns:latest
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          args: [ "-conf", "/etc/coredns/Corefile" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
      volumes:
        - name: config-volume
          configMap:
            name: coredns
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: homelab-dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        etcd homelab.local {
          endpoint http://dns-etcd:2379
          path /skydns
          fallthrough
        }
        forward . 192.168.1.254
        cache 30
        loop
        reload
        loadbalance
    }
---
