all:
  hosts:
    node1-master:
      ansible_host: 192.168.1.137
      ip: 192.168.1.137
      access_ip: 192.168.1.137
    node2-worker:
      ansible_host: 192.168.1.118
      ip: 192.168.1.118
      access_ip: 192.168.1.118
  children:
    kube_control_plane:
      hosts:
        node1-master:
    kube_node:
      hosts:
        node1-master:
        node2-worker:
    etcd:
      hosts:
        node1-master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
